version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: DockerfileApp
    ports:
      - "8082:8082"
    depends_on:
      - migration
    restart: on-failure
  postgresdb:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=house_service
    ports:
      - '1234:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  migration:
    depends_on:
      - postgresdb
    build:
      context: .
      dockerfile: DockerfileMigration

volumes:
  postgres_data:

