DROP TABLE IF EXISTS events;
DROP TABLE IF EXISTS subscriptions;
DROP TABLE IF EXISTS flats;
DROP TABLE IF EXISTS houses;
DROP TABLE IF EXISTS users;
DROP TYPE IF EXISTS user_role;
DROP TYPE IF EXISTS moderation_status;
DROP TYPE IF EXISTS event_type;
