env: "local"
http_server:
    address: ":8082"
    timeout: 4s
    iddle_timeout: 60s
    shutdown_timeout: 10s
db:
    host: "postgresdb"
    port: 5432
    username: "postgres"
    name: "house_service"
    password: "postgres"
jwt:
    token_ttl: 86400s
    secret_key: "test_secret_key"
cache:
    ttl: 60s