  name: Master Workflow - Build and deploy to production
  on:
    pull_request:
      types: 
        - closed
      branches:
        - main
        - master
    workflow_dispatch:
    
  jobs:
    hello-world-job:
      runs-on: ubuntu-latest

      steps:
        - name: Say Hello World
          run: echo "Hello world"


